import { createHash, randomUUID } from "node:crypto";
import { classifyOpportunity } from "./classifier.js";
import { deduplicateOpportunities } from "./dedupe.js";
import { allocateDeepSlots } from "./scheduler.js";
import { createNotifications } from "./notifications.js";
import { createOutbox } from "./outbox.js";

const idFor=(item)=>createHash("sha256").update(`${item.source}:${item.url||item.description}`).digest("hex");
export async function runDiscoveryCycle({store,sources,analyze,maxDeep=12,chatId,thresholds={}}){const startedAt=new Date().toISOString();const summary={id:randomUUID(),startedAt,completed:false,scanned:{},newOpportunities:0,duplicates:0,locallyRejected:0,cheapAnalyzed:0,deepAnalyzed:0,HOT:0,GOOD:0,MAYBE:0,notificationsSent:0,notificationsQueued:0,sourceErrors:[],llmErrors:0,deliveryErrors:0};const raw=[];for(const source of sources){try{const items=await source.fetch();summary.scanned[source.name]=items.length;raw.push(...items);}catch(error){summary.scanned[source.name]=0;summary.sourceErrors.push({source:source.name,code:error.code||"SOURCE_FAILED",message:String(error.message||"failed").slice(0,200)});}}
  const classified=raw.map(item=>classifyOpportunity(item));summary.cheapAnalyzed=classified.length;summary.locallyRejected=classified.filter(x=>x.rejected).length;const accepted=classified.filter(x=>!x.rejected);const unique=deduplicateOpportunities(accepted);summary.duplicates=Math.max(0,accepted.length-unique.length);const unseen=unique.filter(item=>!store.has(idFor(item)));summary.newOpportunities=unseen.length;for(const item of unseen){item.id=idFor(item);store.state.opportunities.unshift(item);store.mark(item.id);}const selected=allocateDeepSlots(unseen,maxDeep);for(const item of selected){try{const result=await analyze(item);Object.assign(item,result,{analysisStatus:"ready"});summary.deepAnalyzed+=1;}catch(error){item.analysisStatus="error";item.analysisError="Analysis temporarily unavailable";summary.llmErrors+=1;}}
  const notices=createNotifications(unseen,chatId,thresholds);const outbox=createOutbox(store);for(const notice of notices)outbox.enqueue(notice);summary.notificationsQueued=notices.length;for(const item of unseen){const band=item.score>=70?"HOT":item.score>=55?"GOOD":item.score>=45?"MAYBE":null;if(band)summary[band]+=1;}summary.completed=true;summary.finishedAt=new Date().toISOString();store.state.opportunities=store.state.opportunities.slice(0,5000);store.state.cycles.unshift(summary);store.state.cycles=store.state.cycles.slice(0,1000);store.save();return summary;}
